export { GradeElevenScoreModel } from './GradeElevenScoreModel'
export { GradeModel } from './GradeModel'
export { GradeTenScoreModel } from './GradeTenScoreModel'
export { GradeTwelveScoreModel } from './GradeTwelveScoreModel'
export { StudentModel } from './StudentModel'
export { SubjectModel } from './SubjectModel'
export { NewsModel, INewsModel } from './NewsModel'